[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.typecheck.mypy",
	"pants.backend.python.lint.docformatter",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.black",
	"pants.backend.experimental.python.lint.pyupgrade"
]

[source]
root_patterns = [
  '/src',
]

[flake8]
config = ".flake8"

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html"]

[mypy]
config = "mypy.ini"

[anonymous-telemetry]
enabled = false